### PR TITLE
fix(ESSNTL-3781): Fixes filter issues in options object

### PR DESCRIPTION
**Pull request by adonispuente**
This PR introduces the refactor of the options object in the Refactor PR (much more readable), and sends parameter correctly to the api endpoints. 

For testing navigate to to /recommendations, and select an recommendation with a high number of systems.
Here add filters like the os system, name, etc. Also make sure sorting is working and updating properly.

### CODE REVIEW

**Review by mkholjuraev — COMMENTED** [review]
LGTM! Selection, sorting, and filters (name, tags, OS) are working as expected, and filter chips are displayed correctly. I have noticed that when the table is empty, sorting is still enabled. This leads to a broken page when I sort by **Last seen**. This is a different issue, do you want to work on another PR?

**Comment by adonispuente** [comment]
@mkholjuraev I'd like to keep the options object. I Think it helps make things a little more readable, especially when you have to run it inside multiple functions, it goes inside the handleRefresh and is spread out in the paginatedRequest function.


I've included a commit to fix the issue with the last_seen column breaking things. The value currently isnt accepted by the api request, so now theres a check in place for it. Similar to the one found in SystemsTable

**Comment by mkholjuraev** [comment]
I confirm that the sorting is working when the table is empty. However, I think we can disable sorting completely when the table is empty. There is no usage.

**Comment by adonispuente** [comment]
> I confirm that the sorting is working when the table is empty. However, I think we can disable sorting completely when the table is empty. There is no usage.
@mkholjuraev 
It seems with the current set up that this will require more of a refactor. I'd like to include it in another PR / make a ticket for it

**Review by mkholjuraev — APPROVED** [review]
LGTM! @adonispuente thanks!

**Pull request merged**
