### PR TITLE
BU directed the removal of vulnerabilities tab

### PR DESCRIPTION
**Pull request by AllenBW**
### see its gone now!
screen shot 2019-01-25 at 10 25 33 am

### CODE REVIEW

**Comment by AllenBW** [comment]
@ncameronbritt thats how the inventory details component work, we can't not have the tab at this time cc @karelhala

**Comment by AllenBW** [comment]
@karelhala maybe we could do something along the lines of... if the component doesn't have a title, and is the only active app, there is no tab for it?

**Comment by AllenBW** [comment]
@ncameronbritt so after that last dep update, this is what we have, no tab!
screen shot 2019-01-27 at 9 31 33 am

**Comment by ncameronbritt** [comment]
Thanks for the update @AllenBW!

**Pull request merged**
