### PR TITLE
Adds rule rating component to rule details page

### PR DESCRIPTION
**Pull request by AllenBW**
this is crawl

fixes https://projects.engineering.redhat.com/browse/RHCLOUD-2958

the thank you appears when feedback is submitted for the first time and disappears after 3 seconds, if you refresh the page and submit more feedback it'll appear than disappear again, what **wont** happen is the thank you always being visible, oh n of course if you have entered feedback before it shows up when yah navigate back to the rule

### this just in! we're doing a different green
Screen Shot 2019-12-06 at 2 20 58 PM

#### hate it
Screen Shot 2019-12-06 at 7 58 51 AM

#### indifferent
Screen Shot 2019-12-06 at 7 58 42 AM

#### love it
Screen Shot 2019-12-06 at 7 58 34 AM

#### hate it with a thank you, it disappears after 3 seconds 
Screen Shot 2019-12-06 at 7 39 14 AM

#### love it with a thank you, it disappears after 3 seconds 
Screen Shot 2019-12-06 at 7 39 05 AM

### CODE REVIEW

**Comment by AllenBW** [comment]
if yah think the green is too dark, we can also go with party green (ie --pf-global--success-color--100)
Screen Shot 2019-12-06 at 8 13 05 AM

**Comment by AllenBW** [comment]
Update, we're gonna go with [`pf-green-400 #3f9c35` from ](https://www.patternfly.org/v3/styles/color-palette/index.html) for visibility
Screen Shot 2019-12-06 at 2 20 58 PM

**Comment by katierik** [comment]
The icons here don't match mocks :( We need the little circle around it to define the shape and account for the fact that the thumbs up/down icons are not very balanced to each other. The visual "center" of the icons aren't the same, so they always look a bit off side by side. 
See here, I drew a line in the visual center of the thumbs up, and it is much lower than the visual center of the thumbs down.
Xnip2019-12-10_17-17-47

Putting them in a circle aligns them because now the visual center is the center of the circle
Xnip2019-12-10_17-19-31

Here's my very inelegant detail: https://codepen.io/katierik/pen/QWwNgrr

**Pull request merged**
