### PR TITLE
chore(RecommendationSystems): clear redux store on unmount

### PR DESCRIPTION
**Pull request by mkholjuraev**
# Description

Associated Jira ticket: # (issue)

Clears the inventory redux on unmount. 

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by mkholjuraev** [comment]
> Why does the Inventory store need to be cleared on unmount?

This is needed to avoid cases when users change tabs, sometimes the content of the previous tab is shown in the next tab for milli-seconds.

**Comment by bastilian** [comment]
@mkholjuraev This feels like it is a workaround for something the Inventory does improperly. Maybe it would be better to investigate a proper fix/feature in the InventoryTable itself.

**Comment by mkholjuraev** [comment]
@bastilian yeah, it seems this [prop]([initialLoading](https://github.com/RedHatInsights/insights-inventory-frontend/blob/910cb2c9ebd7311c25d6980b1894132702b372b6/doc/props_table.md?plain=1#L109)) is used to show initial loading state when the table is initially mounted. I have created a PR in the inventory to add it to immutable devices table

**Review by AsToNlele — APPROVED** [review]
LGTM, thanks for the clarification on the call :smile:

**Comment by bastilian** [comment]
@mkholjuraev Then does the PR in inventory not make this PR obsolete?

**Comment by mkholjuraev** [comment]
> @mkholjuraev Then does the PR in inventory not make this PR obsolete?
@bastilian yes it should be. I am making sure this is obsolete. If it is obsolete, I will close this PR.

**Comment by mkholjuraev** [comment]
Yup, this seems obsolete. Closing

**Pull request closed without merging**
