### PR TITLE
No Recommendations text message reflects the selected rule status filter

### PR DESCRIPTION
**Pull request by mhuth**
Looking at the text for 'Disabled' and 'Red Hat disabled' when there are no recommendations - "None of your connected systems are affected by any known rules." - this doesn't seem to accurately convey why there are no recommendations for 'Disabled' and 'Red Hat disabled'.  This PR changes the text to more accurately reflect why there might be no recommendations for these 2 status options.

When there are 'No Recommendations' for Status of Disabled:
no_disabled_recommendations

When there are No Recommendations for Status of Red Hat disabled:
no_redhat_disabled_recommendations

What do y'all think?  Feel free to shoot me down in flames if you think the old messaging was fine.

### CODE REVIEW

**Comment by terezanovotna** [comment]
thanks for thinking about it @mhuth!

Both sentences make sense, but how about we make them even more consistent? 
For disabled:
Currently there are no disabled recommendations.

**Comment by mhuth** [comment]
> thanks for thinking about it @mhuth!
> 
> Both sentences make sense, but how about we make them even more consistent?
> For disabled:
> Currently there are no disabled recommendations.

Yep, can do @terezanovotna .  My motivation for including the 'you' in the disabled recommendations message was to indicate that this is something that the customer controls.  But they don't control the Red Hat disabled recommendations.

**Review by AllenBW — DISMISSED** [review]
Can we real quick get an update to compiled translations `npm run translations` 🤗

**Comment by mhuth** [comment]
Done.  Sorry, I always forget about the translations :/

**Comment by AllenBW** [comment]
S easy to forget, 🤗 🥇

**Review by AllenBW — APPROVED** [review]
:godmode:

**Pull request merged**
