### PR TITLE
Improve rule details small screen performance 

### PR DESCRIPTION
**Pull request by AllenBW**
####  finally usable at smaller size, looks the same at normal size
Screen Shot 2019-12-10 at 7 37 57 AM
Screen Shot 2019-12-10 at 7 37 40 AM

### CODE REVIEW

**Comment by katierik** [comment]
Oh happy day!
I think the blue line is supposed to also be on the expanded pane, even in mobile.

**Comment by AllenBW** [comment]
oooo it wasn't there previously, probably a pf-table bug, i'll look at it

**Comment by AllenBW** [comment]
@katierik looks like a pf bug, here's a ss of the table expanded component 
Screen Shot 2019-12-10 at 8 09 59 AM

**Comment by katierik** [comment]
Logged bug with PF

**Pull request merged**
