### PR TITLE
Prevents undefined prop error  in listactions component

### PR DESCRIPTION
**Pull request by AllenBW**
I am guilty of not jumping into a pr, #39, and am now paying for the pony. Timey whimey component things are exciting especially when we're doing data processing  in the component, the more permanent fix is gonna be moving most of this logic into actions...

### whats it look like ?!!? but don't worry, 's fixed with this pr
screen shot 2018-09-20 at 5 13 43 pm

### CODE REVIEW

**Comment by ryelo** [comment]
Instead of adding an `or ' '`  to the `PageHeaderTitle`, why not just declare the state inside the constructor like we do with other variables?

```
constructor(props) {
    super(props);
        this.state = {
            cols: [ 'Type', 'Name', 'Reported' ],
            unfilteredRows: [],
            rows: [],
            rule: {
                description: ''
            },
            sortBy: {},
            itemsPerPage: 10,
            page: 1
        };
    . . .
}
```

**Comment by AllenBW** [comment]
Yeah that's another way to solve the problem, not sure its a better way 🤷‍♂️

**Comment by ryelo** [comment]
@AllenBW 🤷‍♂️ I would say let's just keep it consistent for now since that's how we're setting the other state vars. @bmclaughlin ?

**Comment by bmclaughlin** [comment]
@AllenBW @ryelo I vote to go with consistency till we find The Right :tm: solution.

**Pull request merged**
