### PR TITLE
Remove inner router

### PR DESCRIPTION
**Pull request by mkholjuraev**
# Description

Associated Jira ticket: # (issue)

This removes inner routes to improve UX

# How to test the PR

Please include steps to test your PR.

# Before the change

# After the change

# Dependent work link

# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by mkholjuraev** [comment]
@RedHatInsights/team-interact The tests are failing overall because of codecov misconfiguration. But the PR is ready to be reviewed.

**Comment by mkholjuraev** [comment]
@RedHatInsights/team-interact The tests are failing overall because of codecov misconfiguration. But the PR is ready to be reviewed.

**Comment by Fewwy** [comment]
Except for 1 small issue with the CSS alignment, it looks totally fine.
LGTM

**Review by Fewwy — APPROVED** [review]

**Review by dkuc — APPROVED** [review]

**Pull request merged**
