### PR TITLE
Fixes systems page infinity loading issue

### PR DESCRIPTION
**Pull request by AllenBW**
fixes https://issues.redhat.com/browse/ADVISOR-1803

making a real mess here, might need help

@Hyperkid123 is gonna ❤️‍🔥🦤🔪 me

### CODE REVIEW

**Comment by AllenBW** [comment]
biggest issue presently is `TypeError: can't access property "page", e.entities is undefined`

**Comment by Hyperkid123** [comment]
@AllenBW I'll take a look later today.

**Comment by Hyperkid123** [comment]
@AllenBW sorry I was unable to look at this PR :slightly_frowning_face: Hopefully I will have some spare time today.

**Comment by AllenBW** [comment]
closing cuz #840 is closer to right

**Pull request closed without merging**
