### PR TITLE
feat(RHIF-158): adopt new pdf-generator service

### PR DESCRIPTION
**Pull request by mkholjuraev**
# Description

Associated Jira ticket: # [(RHIF-158)](https://issues.redhat.com/browse/RHIF-158)

Adopts the new pdf-generator service. The executive report has been changed to use the new service instead of the shared library. The pdf report on the systems page is removed completely according to the PM's [request](https://redhat-internal.slack.com/archives/C02T90PLJ5V/p1686833724295099).

# How to test the PR

1.  Run the PR locally
2. Navigate to recommendations page
3. click on 'Download executive report' link on the top right.
4. Observe that pdf report gets loaded, notifications are in place. Filename is as expected
5. Navigate to systems page from the navigations sidebar
6. observe that systems table does not have pdf export option available on the toolbar export options 

# Before the change

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [ ] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by AsToNlele** [comment]
Hi, for some reason I'm not able to start the app, I get this error:
image
Are you able to run it?

**Comment by mkholjuraev** [comment]
> Hi, for some reason I'm not able to start the app, I get this error: image Are you able to run it?

Yup, it works fine on my side

**Comment by adonispuente** [comment]
When bringing this down locally, as is, and reinstalling node modules, I am also unable to run this PR

**Review by adonispuente — APPROVED** [review]
This PR works as expected, LGTM!

**Pull request merged**
