### PR TITLE
fix(helpers): fix for missing sort in the url

### PR DESCRIPTION
**Pull request by Fewwy**
# Description

Associated Jira ticket: # (issue)
https://issues.redhat.com/browse/ADVISOR-2956

Open the local dev env
Try to open the link with the missing sort parameter, for example
https://stage.foo.redhat.com:1337/beta/insights/advisor/recommendations?impacting=true&rule_status=enabled&total_risk&limit=20&offset=0&=%3D#SIDs=&tags=

Added codecoverage yml with settings that should remove accidental codecov/patch errors when the codecoverage is decreased by 0.01% or smth like that
# Checklist:

- [x] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Review by adonispuente — COMMENTED** [review]
The actual fix solves the edge case, but why update the package.json and codecov file?

**Comment by Fewwy** [comment]
@adonispuente Codecov.yml is used to describe the behavior of the codecoverage on this repo. I had the issue with codecov/patch failing because the code coverage is reduced by 0.01%. So I decided to read up on the documentation and described the behavior we want to see.

**Comment by Fewwy** [comment]
As you can see from this screenshot if I remove codecov.yml it is failing
image

**Review by mkholjuraev — APPROVED** [review]
LGTM! @Fewwy thank you!

**Comment by Fewwy** [comment]
I showed this PR to Jiri and Adonis and they approved my changes.

**Pull request merged**
