### PR TITLE
Update success color 

### PR DESCRIPTION
**Pull request by LI0131**
This PR is in response to RHCLOUD-8028, and it updates the coloring of the Ansible checks from `--pf-global--success-color--200` to `--pf-global--success-color--100`.

Here's what 200 looks like now:
Screen Shot 2020-07-21 at 10 06 53 AM

Now here's 100:
Screen Shot 2020-07-21 at 10 07 10 AM

Note: this change has been made in the pf4 docs https://www.patternfly.org/v4/documentation/overview/global-css-variables#global-css-variables

### CODE REVIEW

**Comment by LI0131** [comment]
We may want to hold on merging this until I push an update to fec for the inv-insights table so we can update the dep here.

**Comment by AllenBW** [comment]
Can yah also attach ah ss of the rec table ansible check?

**Comment by LI0131** [comment]
@AllenBW of course! 

Screen Shot 2020-07-21 at 10 35 04 AM

**Comment by LI0131** [comment]
Deps should be updated for this now 💯

**Pull request merged**
