### PR TITLE
fix(Tables): Remove Main from the tables

### PR DESCRIPTION
**Pull request by Fewwy**
# Description

Associated Jira ticket: # (issue)
https://issues.redhat.com/browse/RHCLOUD-23126

Please include a summary of the change, what this fixes/creates/improves.
Removed Main component and replaced it with Section

# How to test the PR

Please include steps to test your PR.
Launch it locally and check how it works on stage-beta

# Before the change
A lof of screenshots to put here, I will create a topic in slack

# After the change

# Dependent work link

# Checklist:

- [ ] The commit message has the Jira ticket linked
- [x] PR has a short description
- [ ] Screenshots before and after the change are added
- [ ] Tests for the changes have been added
- [ ] README.md is updated if necessary
- [ ] Needs additional dependent work

### CODE REVIEW

**Comment by gkarat** [comment]
Why is this required? Can we have some description?

**Comment by Fewwy** [comment]
@gkarat Updated the PR description

**Review by gkarat — COMMENTED** [review]
@Hyperkid123, 👋🏼 could you please tell whether using Section is also safe and doesn't contain redux logic behind?

**Comment by Hyperkid123** [comment]
@gkarat yes it is safe. I would even go as far as using the regular `section` HTML elements. If you are not using the `type` prop (which you should not), all the component does is wrap the children in a `section` element.

**Review by gkarat — APPROVED** [review]

**Review by adonispuente — APPROVED** [review]
LGTM!

**Pull request merged**
